version: 2

updates:
- package-ecosystem: gomod
  directory: "/api"
  schedule:
    interval: weekly
  commit-message:
    prefix: "api"
  ignore:
      - dependency-name: "github.com/gustavosbarreto/workflow-test"
- package-ecosystem: gomod
  directory: "/cli"
  schedule:
    interval: weekly
  commit-message:
    prefix: "cli"
  ignore:
      - dependency-name: "github.com/gustavosbarreto/workflow-test"
