version: 2

updates:
- package-ecosystem: gomod
  directory: "/api2"
  schedule:
    interval: weekly
  commit-message:
    prefix: "api2"
  ignore:
      - dependency-name: "github.com/drera-labs/workflow-test"
- package-ecosystem: gomod
  directory: "/cli"
  schedule:
    interval: weekly
  commit-message:
    prefix: "cli"
  ignore:
      - dependency-name: "github.com/drera-labs/workflow-test"
