name: dependabot_pr

on:
  push:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

  pull_request:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

jobs:
  go-mod-tidy:
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update go.sum
        run: |
          cd cli
          go mod tidy
      - name: Create diff artifact
        run: |
          git diff > /tmp/diff
      - uses: actions/upload-artifact@v2
        with:
          name: diff
          path: /tmp/diff
          retention-days: 1
          #'${{ github.event.pull_request.title }}'
