name: Fix Deps

on:
  pull_request:
    branches: [master]

jobs:
  tidyfy:
    if: "contains(github.head_ref, 'refs/head/dependabot/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update go.sum
        run: |
          cd cli
          go mod tidy
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          commit_options: --amend
          branch: ${{ github.head_ref }}