name: go mod tidy for Dependabot

on:
  pull_request:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

permissions:
  contents: write
  pull-requests: write

jobs:
  go-mod-tidy:
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update go.sum
        run: |
          cd cli
          go mod tidy
      - uses: jungwinter/split@v1
        id: event_title_split
        with:
          msg: '${{ github.event.pull_request.title }}'
          seperator: ':'
          maxsplit: 2
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          file_pattern: '**/go.mod **/go.sum'
          commit_message: "cli: ${{ steps.event_title_split.outputs._1}}"
          commit_author: "ShellHub Actions Bot <github-actions-bot@shellhub.io>"