name: go mod tidy for Dependabot

on:
  pull_request:
    branches: [master]
    paths:
      - '**/go.mod'
      - '**/go.sum'

jobs:
  go-mod-tidy:
    if: contains(github.head_ref, 'dependabot/go_modules/') && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Update go.sum
        run: |
          cd cli
          go mod tidy
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          file_pattern: '**/go.mod **/go.sum'
          commit_message: "go mod tidy"
          commit_author: "Luis Gustavo S. Barreto <gustavosbarreto@gmail.com>"