name: nada

on:
  workflow_run:
    workflows:
      - dependabot_pr
    branches:
      - main
    types:
      - requested
      - completed

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Apply diff
        run: cat diff | patch -p1
