name: nada

on:
  workflow_run:
    workflows:
      - dependabot_pr
    types:
      - completed

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: dependabot_pr.yml
          run_id: ${{ github.event.id }}
          name: diff
      - name: Apply diff
        run: cat diff | patch -p1
      - name: Diff
        run: |
          git diff
          git status
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          file_pattern: '**/go.mod **/go.sum'
          #commit_message: "cli: ${{ steps.event_title_split.outputs._1}}"
          commit_author: "ShellHub Actions Bot <github-actions-bot@shellhub.io>"